version: 2.1

jobs:  
  Build_Test:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: Test Server 
          command: npm install --force && npm run test

workflows:
  version: 2
  Build_Publish:
    jobs:
      - Build_Test:
          name: Build & Test
          filters:
            branches:
              only: main